### ISSUE TITLE
Idea: make this into a PyPi package?

### ISSUE THREAD

**Issue by ghost** [chiradeep/lambda-mutex#1]
Nice work, very useful :)

Would it be possible to make it into a PyPi package instead of cloning your code?

**Comment by chiradeep** [comment]
Oh wow, never saw this. Will work on this, thanks

**Comment by chiradeep** [comment]
Submitted.
Let me know if there's a problem
https://pypi.python.org/pypi?:action=display&name=dyndbmutex&version=0.3.1
