### ISSUE TITLE
Warning vs info on prune_expired() and write_lock_item() failure

### ISSUE THREAD

**Issue by SaintFlipper** [chiradeep/lambda-mutex#11]
We have DynamoDbMutex wrapped in a simple time-limited spinlock for Lambda use, and see log warnings in CloudWatch on prune_expired/write_lock_item whenever the lock is already held by another Lambda instance. It doesn't affect lock functionality but means that log monitoring sees a warning and potentially raises an alarm for an expected condition.
Should the logger.warning()s in write_lock_item and prune_expired be downgraded to logger.info()?

**Comment by chiradeep** [comment]
I think that makes sense. Would you be able to submit a PR for this?

**Comment by chiradeep** [comment]
Closed by #12
