### ISSUE TITLE
TTL set to the year 52984

### ISSUE THREAD

**Issue by danielerapati** [chiradeep/lambda-mutex#13]
https://github.com/chiradeep/dyndb-mutex/blob/86f550269ea6572660a9d5f630e5f9cbecf6f1e9/dyndbmutex/dyndbmutex.py#L106

Here `expire_ts` is expressed in milliseconds but TTL is measured in seconds.
A solution could be just: `ttl = expire_ts/1000 + self.ttl_minutes*60`

**Comment by chiradeep** [comment]
Care to send a pull request?
