### ISSUE TITLE
Support region configuration

### ISSUE THREAD

**Issue by lyoungblood** [chiradeep/lambda-mutex#6]
Would it be difficult to allow us to specify which region the Mutex table should live in?  It would improve performance and reduce latency to have the Mutex table in the same region as the system acquiring the lock.  I noticed that it defaults to us-west-2.

Thanks in advance.

**Comment by chiradeep** [comment]
You can already specify `region_name` in the constructor.


` m = DynamoDbMutex('i-8abd832c32', holder=my_name, timeoutms=20 * 1000, region_name='us-east-2')`

**Comment by lyoungblood** [comment]
Thank you, this works perfectly.  This really is a powerful module, and highlights how easily and cost efficiently you can implement something that is traditionally very challenging in computer science (mutex locking) with AWS services.
